#!/usr/bin/env python3
import sys
import os
import time
import subprocess
import ssh_conf

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def show_host():
    print(f"{bcolors.BOLD}Available hosts:{bcolors.ENDC}")
    for i in range(0, len(ssh_conf._HOST)):
        desc = ssh_conf._HOST[i].get('desc', '')
        host = ssh_conf._HOST[i]['host']
        print(f"[{bcolors.WARNING}{i:2d}{bcolors.ENDC}] => {bcolors.OKBLUE}{host:20s}{bcolors.ENDC} {bcolors.FAIL}{desc:20s}{bcolors.ENDC}")
    try:
        index = int(input("\nPlease select the host index to login: "))
    except KeyboardInterrupt:
        print("\n\nCtrl+C pressed...")
        sys.exit(1)
    except ValueError:
        print("Invalid input, please enter a number.")
        sys.exit(1)

    if index < 0 or index >= len(ssh_conf._HOST):
        print(f"Index out of range. Valid range: 0 - {len(ssh_conf._HOST) - 1}")
        sys.exit(1)

    selected = ssh_conf._HOST[index]
    print(f"\nSelected: {bcolors.OKGREEN}{selected['host']}{bcolors.ENDC} ({selected.get('desc', '')})")
    return selected


def print_usage():
    print(f"Usage: {sys.argv[0]} [host]")
    print("  host    : (optional) direct login to specified host address")
    print("  If no host is given, an interactive host list will be shown.")
    sys.exit(1)


def main():
    if len(sys.argv) == 2 and sys.argv[1] in ('-h', '--help'):
        print_usage()

    host_addr = ''
    user = ''
    pwd = ''
    port = '22'

    if len(sys.argv) == 2:
        host_addr = sys.argv[1]
        user = 'userxxx'
        pwd = ssh_conf._PWD[1]
    elif len(sys.argv) == 1:
        host = show_host()
        user = host.get('user', 'root')
        pwd = ssh_conf._PWD[host['pwd']]
        port = host.get('port', '22')
        host_addr = host['host']
    else:
        print_usage()

    cmd = 'login.sh %s@%s %s -p%s' % (user, host_addr, pwd, port)

    for attempt in range(1, 4):
        ret = subprocess.call(cmd, shell=True)
        if ret == 0:
            break
        print(f"{bcolors.WARNING}Connection failed (attempt {attempt}/3), retrying...{bcolors.ENDC}")
        if attempt < 3:
            time.sleep(2)
    else:
        print(f"{bcolors.FAIL}Connection failed after 3 attempts.{bcolors.ENDC}")
        sys.exit(1)


if __name__ == '__main__':
    main()

